name: StrongWolf
version: '1.2.0'
author: BlueNova
description: If AI was to describe this plugin, it would say "Unleash the power of the wolf within your Minecraft world with StrongWolf, the ultimate plugin for enhancing wolf behavior and abilities!"
main: io.github.bluenova.strongWolf.StrongWolfPlugin
api-version: '1.21'
commands:
    strongwolf:
        description: Main command for the StrongWolf plugin.
        usage: /<command> [subcommand]
        aliases: [sw, strong]